/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author jairo
 */
public class loginGeneral extends javax.swing.JFrame {

    /**
     * Creates new form loginGeneral
     */
    public loginGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdmUI = new javax.swing.JButton();
        btnClientUI = new javax.swing.JButton();
        btnEmpUI = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmUI.setText("Administrador");
        btnAdmUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmUIActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        btnClientUI.setText("Cliente");
        btnClientUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientUIActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        btnEmpUI.setText("Empleado");
        btnEmpUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpUIActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Elija una opcion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientUIActionPerformed
        clientUI cui = new clientUI();
        cui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClientUIActionPerformed

    private void btnEmpUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpUIActionPerformed
        employeUI eui = new employeUI();
        eui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpUIActionPerformed

    private void btnAdmUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmUIActionPerformed
        adminUI aui = new adminUI();
        aui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmUIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmUI;
    private javax.swing.JButton btnClientUI;
    private javax.swing.JButton btnEmpUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
